### ISSUE TITLE
About training dataset

### ISSUE THREAD

**Issue by xizero00** [zhiqiangdon/pose-adv-aug#1]
Hi @zhiqiangdon 
Thank your for sharing your nice work.
I want to cite your work and need some details.

In your paper
"Jointly Optimize Data Augmentation and Network Training: Adversarial Data Augmentation in Human Pose Estimation", 
Is the table 3's result trained using the MPII+LSP dataset or Only LSP dataset?

**Comment by zhiqiangdon** [comment]
Hi,

Thanks for your interest. We use MPII+LSP following the setup of paper "Multi-context attention for human pose estimation".
